apiVersion: batch/v1
kind: CronJob
metadata:
  name: permalink-db-backup
spec:
  schedule: "{{ .Values.helm.cronjob.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: postgres-backup
              persistentVolumeClaim:
                claimName: postgres-backup-pvc
            - name: permalink-scripts
              configMap:
                name: permalink-scripts
                defaultMode: 0777
          containers:
            - name: permalink-db-backup
              resources:
                limits:
                  memory: "256Mi"
              image: postgres:17.5
              envFrom:
                - configMapRef:
                    name: db-config
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-creds
                      key: postgres-user
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-creds
                      key: postgres-password
              command:
                - /scripts/backup_db.sh
              volumeMounts:
                - name: postgres-backup
                  mountPath: /var/backups
                - name: permalink-scripts
                  mountPath: /scripts
