apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:

      containers:
      - name: postgresdb
        resources:
          limits:
            memory: "2Gi"
        image: "{{ .Values.helm.postgres.image }}"
        envFrom:
          - configMapRef:
              name: db-config
        env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: postgres-password

        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgresdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresdb
