{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "postgres-admin-creds") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $postgresPass := (get $secretData "postgres-admin-password") | default (randAlphaNum 32 | b64enc) }}
{{- $postgresAdminUser := (get $secretData "postgres-admin-password") | default (randAlphaNum 32 | b64enc) }}

kind: Secret
apiVersion: v1
metadata:
  name: postgres-creds
data:  
  postgres-admin-user: {{ $postgresAdminUser | quote }}
  postgres-admin-password: {{ $postgresPass | quote }}
type: Opaque
