{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "postgres-creds") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $postgresPass := (get $secretData "postgres-user") | default (randAlphaNum 32 | b64enc) }}
{{- $postgresUser := (get $secretData "postgres-password") | default (randAlphaNum 32 | b64enc) }}

kind: Secret
apiVersion: v1
metadata:
  name: postgres-creds
data:  
  postgres-user: {{ $postgresUser | quote }}
  postgres-password: {{ $postgresPass | quote }}
type: Opaque
