{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
    name: permalink-web-secret.yaml
type: Opaque 
stringData:
    NEXTCLOUD_CLIENT_ID: "{{ .Values.web.NEXTCLOUD_CLIENT_ID }}"
    NEXTCLOUD_SECRET_ID: "{{ .Values.web.NEXTCLOUD_SECRET_ID }}"

    NEXTCLOUD_ADMIN_USER: "{{ .Values.web.NEXTCLOUD_ADMIN_USER }}"
    NEXTCLOUD_ADMIN_PASSWORD: "{{ .Values.web.NEXTCLOUD_ADMIN_PASSWORD }}"

    OIDC_RP_CLIENT_ID: "{{ .Values.oidc.clientId }}"
    OIDC_RP_CLIENT_SECRET: "{{ .Values.oidc.clientSecret }}"
{{- end }}

