apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: permalink-static
spec:
  storageClassName: cephfs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
        storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
        storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
        storage: 3Gi
