{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "permalink-web-secret") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $djangoSuperUserPass := (get $secretData "DJANGO_SUPERUSER_PASSWORD" | b64dec) | default (randAlphaNum 32 ) }}
{{- $djangoSuperUserUsername := (get $secretData "DJANGO_SUPERUSER_USERNAME" | b64dec) | default (randAlphaNum 32 ) }}
{{- $djangoSecretkey := (get $secretData "SECRET_KEY" | b64dec) | default (randAlphaNum 50 ) }}

apiVersion: v1
kind: Secret
metadata:
    name: permalink-web-secret
type: Opaque 
stringData:
    NEXTCLOUD_CLIENT_ID: "{{ .Values.web.NEXTCLOUD_CLIENT_ID }}"
    NEXTCLOUD_SECRET_ID: "{{ .Values.web.NEXTCLOUD_SECRET_ID }}"

    NEXTCLOUD_ADMIN_USER: "{{ .Values.web.NEXTCLOUD_ADMIN_USER }}"
    NEXTCLOUD_ADMIN_PASSWORD: "{{ .Values.web.NEXTCLOUD_ADMIN_PASSWORD }}"

    OIDC_CLIENT_ID: "{{ .Values.oidc.clientId }}"
    OIDC_CLIENT_SECRET: "{{ .Values.oidc.clientSecret }}"
    SECRET_KEY: "{{ $djangoSecretkey }}"
    DJANGO_SUPERUSER_USERNAME: "{{ $djangoSuperUserUsername }}"
    DJANGO_SUPERUSER_PASSWORD: "{{ $djangoSuperUserPass }}"
