services:
  db:
    container_name: postgresdb
    image: postgres:17.5
    restart: always
    env_file:
      - ./env_configs/db_conn.env
    volumes:
      - postgredata:/var/lib/postgresql/data
    expose:
      - 5432

  django:
    container_name: django-permalink
    build:
      context: ./permalink
      # target: prd
      target: dev
    env_file:
      - ./env_configs/db_conn.env
      - ./env_configs/env_dev.env
    volumes:
      - ./permalink/:/app/
    #   - mediaroot:/app/media_root
      - static_root:/app/static_root
      - pylab_logs:/var/log/
    expose:
      - 8000
    extra_hosts:
      - nextcloud.local:host-gateway
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        SITE_DOMAIN_ARG: link.ulb.be
    environment:
      SITE_DOMAIN: link.ulb.be
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
      # - "443:443"
    volumes:
    #   - mediaroot:/app/media_root
      - static_root:/app/static_root
    depends_on:
      - django

volumes:
  postgredata:
  static_root:
  pylab_logs:
