# Generated by Django 5.2 on 2025-06-04 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('target_url', models.URLField(verbose_name='Target URL')),
                ('path', models.CharField()),
                ('expiration', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='share', to='link.share')),
            ],
        ),
    ]
