# Generated by Django 5.2 on 2026-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
