# Generated by Django 5.2 on 2025-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_remove_link_creation_date_link_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(max_length=50, unique=True, verbose_name='Token'),
        ),
    ]
