# Generated by Django 5.2 on 2025-04-15 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_alter_link_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('user', 'token')},
        ),
    ]
