# Generated by Django 5.2 on 2025-05-08 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_link_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Token'),
        ),
    ]
