# Generated by Django 5.2 on 2025-05-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_alter_link_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(verbose_name='Target URL')),
                ('path', models.CharField()),
                ('expiration', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='target_url',
        ),
        migrations.AddField(
            model_name='link',
            name='sharelink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharelink', to='link.sharelink'),
        ),
    ]
