# Generated by Django 5.2 on 2025-05-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_sharelink_remove_link_target_url_link_sharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(verbose_name='Target URL')),
                ('path', models.CharField()),
                ('expiration', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='sharelink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to='link.share'),
        ),
        migrations.DeleteModel(
            name='ShareLink',
        ),
    ]
