# Generated by Django 5.2 on 2025-05-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_share_alter_link_sharelink_delete_sharelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='uid',
            new_name='uuid',
        ),
    ]
