# Generated by Django 5.2 on 2025-05-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_rename_uid_share_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='uuid',
            new_name='uid',
        ),
    ]
