# Generated by Django 5.2 on 2025-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_rename_uuid_share_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='expiration',
            field=models.DateField(null=True),
        ),
    ]
