# Generated by Django 5.2 on 2025-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0010_alter_share_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
