# Generated by Django 5.2 on 2025-05-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0011_alter_share_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='sharelink',
            new_name='share',
        ),
    ]
