# Generated by Django 5.2 on 2025-05-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0012_rename_sharelink_link_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='link.share'),
        ),
    ]
