# Generated by Django 5.2 on 2025-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0013_alter_link_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
