# Generated by Django 5.2 on 2025-05-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0014_alter_share_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='share', to='link.share'),
        ),
    ]
