# Generated by Django 5.2 on 2025-05-21 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0015_alter_link_share'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Token'),
        ),
    ]
