apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "permalink"
  DATABASE_HOST: "postgresdb"
  DATABASE_PORT: "5432"

