acme_server: https://acme-v02.api.letsencrypt.org/directory/

nginx:
  image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/nginx:prd

web:

  ACME: "True"

  DEBUG: "False"
  SECURE_SSL_REDIRECT: "False"

  SITE_PROTOCOL : "https"
  SITE_DOMAIN: "permalink.ulb.be"
  CSRF_TRUSTED_ORIGINS: "https://permalink.ulb.be,https://mycloud.ulb.be"

  # no trailling slash for nextcloud_url
  NEXTCLOUD_URL: https://mycloud.ulb.be

  # define in local values-secret.yaml or inside the permalink-web-secret
  SECRET_KEY: ""
  NEXTCLOUD_CLIENT_ID: ""
  NEXTCLOUD_SECRET_ID: ""
  NEXTCLOUD_ADMIN_USER: ""
  NEXTCLOUD_ADMIN_PASSWORD: ""

  image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/permalink:prd

oidc:
  clientId: ""
  clientSecret: ""
  discoveryEndpoint: "https://auth.ulb.be/oidc/.well-known/openid-configuration"
  authorizationEndpoint: "https://auth.ulb.be/oidc/oidcAuthorize"
  tokenEndpoint: "https://auth.ulb.be/oidc/oidcAccessToken"
  userEndpoint: "https://auth.ulb.be/oidc/oidcProfile"
  jwksEndpoint: "https://auth.ulb.be/oidc/jwks"
  logoutEndpoint: "https://auth.ulb.be/oidc/oidcLogout"
