acme_server: https://acme-v02.api.letsencrypt.org/directory/

restore_pod: false
ACME: false

helm:
  nginx:
    image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/nginx:dev
  cronjob:
    schedule: "*/10 * * * *"
  postgres:
    image: docker.io/bitnamilegacy/postgresql:17.6.0

web:

  DEBUG: "True"
  SECURE_SSL_REDIRECT: "False"

  SITE_PROTOCOL: "https"
  SITE_DOMAIN: "permalink.apps.dev.okd.hpda.ulb.ac.be"
  CSRF_TRUSTED_ORIGINS: "https://permalink.apps.dev.okd.hpda.ulb.ac.be,https://nc-test.ulb.ac.be"

  # no trailling slash for nextcloud_url
  NEXTCLOUD_URL: https://nc-test.ulb.ac.be
  NEXTCLOUD_CLIENT_ID: "5r3jSgyPDkxHxj5HrDnLjclw7ROXKx8NxovMiLUgQ5oF3FneHUP0PvZt6D4IJWkc"
  NEXTCLOUD_SECRET_ID: "sbfAxfssSmYOLNfCm4Qih2Mpxyfi1WEYsgHPl79wYpyWF8ljhEU9tEOyvxAUtBUM"

  NEXTCLOUD_ADMIN_USER: "nc_admin"
  NEXTCLOUD_ADMIN_PASSWORD: "n9UeWq24JkA1rLzX"

  DJANGO_SUPERUSER_USERNAME: "admin_permalink"
  DJANGO_SUPERUSER_PASSWORD: "admin_password"

  image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/permalink:dev

oidc:
  clientId: "Permalink_clientid_dev"
  clientSecret: "Permalink_secret_dev"
  discoveryEndpoint: "https://auth-dev.ulb.be/oidc/.well-known/openid-configuration"
  authorizationEndpoint: "https://auth-dev.ulb.be/oidc/oidcAuthorize"
  tokenEndpoint: "https://auth-dev.ulb.be/oidc/oidcAccessToken"
  userEndpoint: "https://auth-dev.ulb.be/oidc/oidcProfile"
  jwksEndpoint: "https://auth-dev.ulb.be/oidc/jwks"
  logoutEndpoint: "https://auth-dev.ulb.be/oidc/oidcLogout"
