
acme_server: https://acme-v02.api.letsencrypt.org/directory/

nginx:
  image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/nginx:dev

web:

  DEBUG: "True"
  SECURE_SSL_REDIRECT: "False"

  SITE_PROTOCOL: "https"
  SITE_DOMAIN: "permalink.apps.dev.okd.hpda.ulb.ac.be"
  CSRF_TRUSTED_ORIGINS: "https://permalink.apps.dev.okd.hpda.ulb.ac.be,https://nc-test.ulb.ac.be"

  SECRET_KEY: "django-t:55_t5&e(l@ne*(r2x34-44wch895qsr4v2nsjteq2br2e(s)"

  # no trailling slash for nextcloud_url
  NEXTCLOUD_URL: https://nc-test.ulb.ac.be
  NEXTCLOUD_CLIENT_ID: "K0iXVR1TOeQnNmJKbYjLsHsCxCz4otdJUhEP2NbCcDRmPvrgeIaReOk33wlkm3g4"
  NEXTCLOUD_SECRET_ID: "QVug02cIhHMwIj0SYkPpk4TkBOMlPSkqWBwbnnRb3Dn01ALMkx6ymstikL3HTucC"

  NEXTCLOUD_ADMIN_USER: "ncadmin"
  NEXTCLOUD_ADMIN_PASSWORD: "n9UeWq24JkA1rLzX"

  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_USERNAME: "admin_permalink"
  DJANGO_SUPERUSER_PASSWORD: "admin_password"

  image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/permalink:dev

oidc:
  clientId: "Permalink_clientid_dev"
  clientSecret: "Permalink_secret_dev"
  discoveryEndpoint: "https://auth-dev.ulb.be/oidc/.well-known/openid-configuration"
  authorizationEndpoint: "https://auth-dev.ulb.be/oidc/oidcAuthorize"
  tokenEndpoint: "https://auth-dev.ulb.be/oidc/oidcAccessToken"
  userEndpoint: "https://auth-dev.ulb.be/oidc/oidcProfile"
  jwksEndpoint: "https://auth-dev.ulb.be/oidc/jwks"
  logoutEndpoint: "https://auth-dev.ulb.be/oidc/oidcLogout"
