acme_server: https://acme-v02.api.letsencrypt.org/directory/

restore_pod: false
ACME: true

helm:
  nginx:
    image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/nginx:prd
  cronjob:
    schedule: "27 */5 * * *"
  postgres:
    image: docker.io/bitnamilegacy/postgresql:17.6.0

web:

  DEBUG: "False"
  SECURE_SSL_REDIRECT: "False"

  SITE_PROTOCOL : "https"
  SITE_DOMAIN: "permalink.ulb.be"
  CSRF_TRUSTED_ORIGINS: "https://permalink.ulb.be,https://mycloud.ulb.be"

  # no trailling slash for nextcloud_url
  NEXTCLOUD_URL: https://mycloud.ulb.be

  image: registry.gitlab.ulb.be/pole-techno/okd-apps/django-permalink/permalink:prd

oidc:
  discoveryEndpoint: "https://auth.ulb.be/oidc/.well-known/openid-configuration"
  authorizationEndpoint: "https://auth.ulb.be/oidc/oidcAuthorize"
  tokenEndpoint: "https://auth.ulb.be/oidc/oidcAccessToken"
  userEndpoint: "https://auth.ulb.be/oidc/oidcProfile"
  jwksEndpoint: "https://auth.ulb.be/oidc/jwks"
  logoutEndpoint: "https://auth.ulb.be/oidc/oidcLogout"
